### ISSUE TITLE
[Caverns and Chasms] and Dungeon Plus error

### ISSUE THREAD

**Issue by Pet-Slime** [team-abnormals/indev-issues#10]
Having dungeon plus and Caverns and Chasms together at once causes dungeon's plus to no longer be able to loot inject. Works fine without Caverns and Chasms. 

[Caverns__Chasms_and_Dungeon_Plus_together_error_log.txt](https://github.com/team-abnormals/indev-issues/files/6720582/Caverns__Chasms_and_Dungeon_Plus_together_error_log.txt)

**Comment by Pet-Slime** [comment]
the error

```
[24Jun2021 09:12:09.583] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 6
	Listeners:
		0: NORMAL
		1: ASM: class com.legacy.dungeons_plus.DPEvents lootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$3052/0x0000000800c9cc40@7d4e7683
		3: ASM: class com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		4: ASM: class vectorwing.farmersdelight.setup.CommonEventHandler onLootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		5: ASM: class com.minecraftabnormals.upgrade_aquatic.core.events.LootEvents onInjectLoot(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		6: ASM: class com.minecraftabnormals.caverns_and_chasms.core.other.CCEvents onInjectLoot(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		7: ASM: vazkii.quark.content.tools.module.AncientTomesModule@5732ac93 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		8: LOWEST
		9: ASM: class com.minecraftabnormals.abnormals_core.core.registry.LootInjectionRegistry onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
java.lang.NullPointerException
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at com.minecraftabnormals.caverns_and_chasms.core.other.CCEvents.addEntry(CCEvents.java:560)
	at com.minecraftabnormals.caverns_and_chasms.core.other.CCEvents.onInjectLoot(CCEvents.java:551)
	at net.minecraftforge.eventbus.ASMEventHandler_342_CCEvents_onInjectLoot_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at com.legacy.dungeons_plus.DPEvents.lootTableLoad(DPEvents.java:78)
	at net.minecraftforge.eventbus.ASMEventHandler_4_DPEvents_lootTableLoad_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:666)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:891)
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712)
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685)
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260)
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205)
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33)
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16)
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136)
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27)
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87)
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85)
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109)
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[24Jun2021 09:12:09.587] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.legacy.dungeons_plus.DPEvents lootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$3052/0x0000000800c9cc40@7d4e7683
		3: ASM: class com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		4: ASM: class vectorwing.farmersdelight.setup.CommonEventHandler onLootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		5: ASM: class com.minecraftabnormals.upgrade_aquatic.core.events.LootEvents onInjectLoot(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		6: ASM: class com.minecraftabnormals.caverns_and_chasms.core.other.CCEvents onInjectLoot(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		7: ASM: vazkii.quark.content.tools.module.AncientTomesModule@5732ac93 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		8: LOWEST
		9: ASM: class com.minecraftabnormals.abnormals_core.core.registry.LootInjectionRegistry onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
java.lang.NullPointerException
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at com.minecraftabnormals.caverns_and_chasms.core.other.CCEvents.addEntry(CCEvents.java:560)
	at com.minecraftabnormals.caverns_and_chasms.core.other.CCEvents.onInjectLoot(CCEvents.java:551)
	at net.minecraftforge.eventbus.ASMEventHandler_342_CCEvents_onInjectLoot_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at com.legacy.dungeons_plus.DPEvents.lootTableLoad(DPEvents.java:78)
	at net.minecraftforge.eventbus.ASMEventHandler_4_DPEvents_lootTableLoad_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:666)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:891)
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712)
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685)
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260)
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205)
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33)
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16)
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136)
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27)
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87)
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85)
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109)
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[24Jun2021 09:12:09.651] [Render thread/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table dungeons_plus:chests/vanilla_dungeon
java.lang.NullPointerException: null
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:?]
	at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:418) ~[?:?]
	at com.minecraftabnormals.caverns_and_chasms.core.other.CCEvents.addEntry(CCEvents.java:560) ~[caverns_and_chasms:1.0.0]
	at com.minecraftabnormals.caverns_and_chasms.core.other.CCEvents.onInjectLoot(CCEvents.java:551) ~[caverns_and_chasms:1.0.0]
	at net.minecraftforge.eventbus.ASMEventHandler_342_CCEvents_onInjectLoot_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at com.legacy.dungeons_plus.DPEvents.lootTableLoad(DPEvents.java:78) ~[dungeons_plus:1.1.5]
	at net.minecraftforge.eventbus.ASMEventHandler_4_DPEvents_lootTableLoad_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:666) ~[forge:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:891) ~[forge:?]
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38) ~[?:?]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) ~[?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712) ~[?:?]
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685) ~[?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260) ~[?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205) ~[?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?]
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.32.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.32.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
```
